'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchlumpfSoft.Controls.SevenSegmentControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt die Hintergrundfarbe des Controls fest oder gibt diese zurück. ähnelt.
        '''</summary>
        Friend ReadOnly Property BackColorDescription() As String
            Get
                Return ResourceManager.GetString("BackColorDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Control zum Anzeigen einer Ziffernfolge als 7-Segmentanzeige. ähnelt.
        '''</summary>
        Friend ReadOnly Property ClassDescriptionSevSegMultiDigit() As String
            Get
                Return ResourceManager.GetString("ClassDescriptionSevSegMultiDigit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Control zum Anzeigen einer Ziffer als 7-Segmentanzeige. ähnelt.
        '''</summary>
        Friend ReadOnly Property ClassDescriptionSevSegSingleDigit() As String
            Get
                Return ResourceManager.GetString("ClassDescriptionSevSegSingleDigit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt an, ob die Doppelpunkt-LEDs aktiv sind. ähnelt.
        '''</summary>
        Friend ReadOnly Property ColonActiveDescription() As String
            Get
                Return ResourceManager.GetString("ColonActiveDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt ein benutzerdefiniertes Bitmuster fest, das in den  sieben Segmenten angezeigt werden soll. Dies ist ein ganzzahliger Wert, bei dem die Bits 0 bis 6 den jeweiligen LED-Segmenten entsprechen. ähnelt.
        '''</summary>
        Friend ReadOnly Property CustomBitPatternDescription() As String
            Get
                Return ResourceManager.GetString("CustomBitPatternDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt an, ob die Dezimalpunkt-LED aktiv ist. ähnelt.
        '''</summary>
        Friend ReadOnly Property DecimalPointActiveDescription() As String
            Get
                Return ResourceManager.GetString("DecimalPointActiveDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl der Digits in diesem Control. ähnelt.
        '''</summary>
        Friend ReadOnly Property DigitCountDescription() As String
            Get
                Return ResourceManager.GetString("DigitCountDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auffüllung, die für jedes Digit im Control gilt. ähnelt.
        '''</summary>
        Friend ReadOnly Property DigitPaddingDescription() As String
            Get
                Return ResourceManager.GetString("DigitPaddingDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt das anzuzeigende Zeichen fest oder gibt dieses zurück. ähnelt.
        '''</summary>
        Friend ReadOnly Property DigitValueDesciption() As String
            Get
                Return ResourceManager.GetString("DigitValueDesciption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt die Vordergrundfarbe der Segmente des Controls fest oder gibt diese zurück. ähnelt.
        '''</summary>
        Friend ReadOnly Property ForeColorDescription() As String
            Get
                Return ResourceManager.GetString("ForeColorDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt die Farbe inaktiver Segmente fest oder gibt diese zurück. ähnelt.
        '''</summary>
        Friend ReadOnly Property InactiveColorDescription() As String
            Get
                Return ResourceManager.GetString("InactiveColorDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scherkoeffizient für die Kursivschrift der Anzeige. ähnelt.
        '''</summary>
        Friend ReadOnly Property ItalicFactorDescription() As String
            Get
                Return ResourceManager.GetString("ItalicFactorDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt die Breite der LED-Segmente fest oder gibt diese zurück. ähnelt.
        '''</summary>
        Friend ReadOnly Property SegmentWidthDescription() As String
            Get
                Return ResourceManager.GetString("SegmentWidthDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SevSegMultiDigit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevSegMultiDigit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SevSegSingleDigit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevSegSingleDigit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt an, ob die Doppelpunkt-LEDs angezeigt werden. ähnelt.
        '''</summary>
        Friend ReadOnly Property ShowColonDescription() As String
            Get
                Return ResourceManager.GetString("ShowColonDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt an, ob die Dezimalpunkt-LED angezeigt wird. ähnelt.
        '''</summary>
        Friend ReadOnly Property ShowDecimalPointDescription() As String
            Get
                Return ResourceManager.GetString("ShowDecimalPointDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der auf dem Control anzuzeigende Wert. ähnelt.
        '''</summary>
        Friend ReadOnly Property ValueDescription() As String
            Get
                Return ResourceManager.GetString("ValueDescription", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
