'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchlumpfSoft.Controls.AniGifControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AniGif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AniGif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt fest ob die Animation sofort nach dem laden gestartet wird. ähnelt.
        '''</summary>
        Friend ReadOnly Property AutoPlayDescription() As String
            Get
                Return ResourceManager.GetString("AutoPlayDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Control zum Anzeigen von animierten Grafiken. ähnelt.
        '''</summary>
        Friend ReadOnly Property ClassDescription() As String
            Get
                Return ResourceManager.GetString("ClassDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt fest ob die benutzerdefinierte Anzeigegeschwindigkeit oder die in der Datei festgelegte Geschwindigkeit benutzt wird. ähnelt.
        '''</summary>
        Friend ReadOnly Property CustomDisplaySpeedDescription() As String
            Get
                Return ResourceManager.GetString("CustomDisplaySpeedDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt die benutzerdefinierte Anzeigegeschwindigkeit in Bildern/Sekunde fest wenn CustomDisplaySpeed auf True festgelegt ist. ähnelt.
        '''</summary>
        Friend ReadOnly Property FramesPerSecondDescription() As String
            Get
                Return ResourceManager.GetString("FramesPerSecondDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt die animierte Gif-Grafik zurück oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property GifDescription() As String
            Get
                Return ResourceManager.GetString("GifDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibt die Art wie die Grafik angezeigt wird zurück oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property GifSizeModeDescription() As String
            Get
                Return ResourceManager.GetString("GifSizeModeDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst wenn die Grafik nicht animiert werden kann. ähnelt.
        '''</summary>
        Friend ReadOnly Property NoAnimationDescription() As String
            Get
                Return ResourceManager.GetString("NoAnimationDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Legt den Zoomfaktor fest wenn GifSizeMode auf Zoom festgelegt ist. ähnelt.
        '''</summary>
        Friend ReadOnly Property ZoomFactorDescription() As String
            Get
                Return ResourceManager.GetString("ZoomFactorDescription", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
