'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchlumpfSoft.Controls.WizardControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tritt auf, nachdem die Seiten des Assistenten gewechselt wurden, und gibt dem Benutzer die Möglichkeit, die neue Seite einzurichten. ähnelt.
        '''</summary>
        Friend ReadOnly Property AfterSwitchPagesDescription() As String
            Get
                Return ResourceManager.GetString("AfterSwitchPagesDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tritt auf, bevor die Seiten des Assistenten gewechselt werden, um dem Benutzer die Möglichkeit zur Validierung zu geben. ähnelt.
        '''</summary>
        Friend ReadOnly Property BeforeSwitchPagesDescription() As String
            Get
                Return ResourceManager.GetString("BeforeSwitchPagesDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend ReadOnly Property ButtonCancelText_PageCustom() As String
            Get
                Return ResourceManager.GetString("ButtonCancelText_PageCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fertigstellen ähnelt.
        '''</summary>
        Friend ReadOnly Property ButtonCancelText_PageFinish() As String
            Get
                Return ResourceManager.GetString("ButtonCancelText_PageFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        '''</summary>
        Friend ReadOnly Property ButtonCancelText_Standard() As String
            Get
                Return ResourceManager.GetString("ButtonCancelText_Standard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tritt auf wenn der Benutzer auf Abbrechen geklickt hat. ähnelt.
        '''</summary>
        Friend ReadOnly Property CancelDesription() As String
            Get
                Return ResourceManager.GetString("CancelDesription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein Control zum erstellen eines Assistenen ähnelt.
        '''</summary>
        Friend ReadOnly Property ClassDescription() As String
            Get
                Return ResourceManager.GetString("ClassDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Beschreibung der Assistentenseite ab oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property DescriptionDescription() As String
            Get
                Return ResourceManager.GetString("DescriptionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft ab oder legt fest, an welcher Kante des übergeordneten Containers ein Steuerelement angedockt ist. ähnelt.
        '''</summary>
        Friend ReadOnly Property DockDescription() As String
            Get
                Return ResourceManager.GetString("DockDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tritt auf, wenn der Assistent abgeschlossen ist, und gibt dem Benutzer die Möglichkeit, zusätzliche Aufgaben zu erledigen. ähnelt.
        '''</summary>
        Friend ReadOnly Property FinishDescription() As String
            Get
                Return ResourceManager.GetString("FinishDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Schriftart ab, die zum Anzeigen der Beschreibung einer Standardseite verwendet wird, oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property HeaderFontDescription() As String
            Get
                Return ResourceManager.GetString("HeaderFontDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Schriftart ab, die zum Anzeigen des Titels einer Standardseite verwendet wird, oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property HeaderTitleFontDescription() As String
            Get
                Return ResourceManager.GetString("HeaderTitleFontDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tritt auf, wenn der Benutzer auf die Hilfeschaltfläche klickt. ähnelt.
        '''</summary>
        Friend ReadOnly Property HelpDescription() As String
            Get
                Return ResourceManager.GetString("HelpDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft das in der Kopfzeile der Standardseiten angezeigte Bild ab oder legt dieses fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property ImageHeaderDesription() As String
            Get
                Return ResourceManager.GetString("ImageHeaderDesription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft das auf den Begrüßungs- und Abschlussseiten angezeigte Bild ab oder legt es fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property ImageWelcomeDescription() As String
            Get
                Return ResourceManager.GetString("ImageWelcomeDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Auflistung der Assistentenseiten in diesem Registerkartensteuerelement ab. ähnelt.
        '''</summary>
        Friend ReadOnly Property PagesCollectionDescription() As String
            Get
                Return ResourceManager.GetString("PagesCollectionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft den Stil der Assistentenseite ab oder legt diesen fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property StyleDescription() As String
            Get
                Return ResourceManager.GetString("StyleDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft den Titel der Assistentenseite ab oder legt diesen fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property TitleDescription() As String
            Get
                Return ResourceManager.GetString("TitleDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Sichtbarkeit Status der Hilfeschaltfläche ab oder legt diesen fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property VisibleHelpDescription() As String
            Get
                Return ResourceManager.GetString("VisibleHelpDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Schriftart ab, die zum Anzeigen der Beschreibung einer Begrüßungs- oder Abschlussseite verwendet wird, oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property WelcomeFontDescription() As String
            Get
                Return ResourceManager.GetString("WelcomeFontDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WelcomeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WelcomeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruft die Schriftart ab, die zum Anzeigen des Titels einer Begrüßungs- oder Abschlussseite verwendet wird, oder legt diese fest. ähnelt.
        '''</summary>
        Friend ReadOnly Property WelcomeTitleFontDescription() As String
            Get
                Return ResourceManager.GetString("WelcomeTitleFontDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
