'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TestApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim105() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim105", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim106() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim106", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim107() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim107", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim108() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim108", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim109() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim109", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim112() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim112", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim113() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim113", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim114() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim114", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim115() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim115", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim116() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim116", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim117() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim117", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim118() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim118", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anim119() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anim119", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationComboBoxItem1() As String
            Get
                Return ResourceManager.GetString("AnimationComboBoxItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zentriert ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationComboBoxItem2() As String
            Get
                Return ResourceManager.GetString("AnimationComboBoxItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationComboBoxItem3() As String
            Get
                Return ResourceManager.GetString("AnimationComboBoxItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gefüllt ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationComboBoxItem4() As String
            Get
                Return ResourceManager.GetString("AnimationComboBoxItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Animation Nr.: {0} ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationNumberText() As String
            Get
                Return ResourceManager.GetString("AnimationNumberText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standardanimation ähnelt.
        '''</summary>
        Friend ReadOnly Property AnimationStandardText() As String
            Get
                Return ResourceManager.GetString("AnimationStandardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Laufwerk {0} wurde hinzugefügt. ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine1() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Datenträger hat die Bezeichnung {0} und ist vom Typ {1}. ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine2() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Format ist {0} und der gesamte Speicherplatz beträgt {1} Bytes. ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine3() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Laufwerk ist bereit und der freie Speicherplatz beträgt {0} Bytes. ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine4() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Laufwerk ist nicht bereit ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine5() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Laufwerk {0} wurde entfernt. ähnelt.
        '''</summary>
        Friend ReadOnly Property DriveWatcherMsgLine6() As String
            Get
                Return ResourceManager.GetString("DriveWatcherMsgLine6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der gewählte Eintragsname existiert bereits!
        '''Bitte wählen sie einen anderen Name. ähnelt.
        '''</summary>
        Friend ReadOnly Property ErrorMsgEntryNameExist() As String
            Get
                Return ResourceManager.GetString("ErrorMsgEntryNameExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der gewählte Abschnittsname existiert bereits!
        '''Bitte wählen sie einen anderen Name. ähnelt.
        '''</summary>
        Friend ReadOnly Property ErrorMsgSectionNameExist() As String
            Get
                Return ResourceManager.GetString("ErrorMsgSectionNameExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dateiinhalt: ähnelt.
        '''</summary>
        Friend ReadOnly Property IniFile_ContentViewTitle() As String
            Get
                Return ResourceManager.GetString("IniFile_ContentViewTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die INI - Dateien (*.ini)|*.ini ähnelt.
        '''</summary>
        Friend ReadOnly Property IniFile_FileDialogFilter() As String
            Get
                Return ResourceManager.GetString("IniFile_FileDialogFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die INI - Datei öffnen ähnelt.
        '''</summary>
        Friend ReadOnly Property IniFile_OpenFileDialogTitle() As String
            Get
                Return ResourceManager.GetString("IniFile_OpenFileDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die INI - Datei speichern unter ähnelt.
        '''</summary>
        Friend ReadOnly Property IniFile_SaveFileDialogTitle() As String
            Get
                Return ResourceManager.GetString("IniFile_SaveFileDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler! ähnelt.
        '''</summary>
        Friend ReadOnly Property MsgBoxTitleError() As String
            Get
                Return ResourceManager.GetString("MsgBoxTitleError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Bild kann nicht animiert werden. ähnelt.
        '''</summary>
        Friend ReadOnly Property NoAnimationMsg() As String
            Get
                Return ResourceManager.GetString("NoAnimationMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Animation ähnelt.
        '''</summary>
        Friend ReadOnly Property NoAnimationTitle() As String
            Get
                Return ResourceManager.GetString("NoAnimationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxDesignItem1() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxDesignItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbig ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxDesignItem2() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxDesignItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxDesignItem3() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxDesignItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Infosymbol ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxStylesItem1() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxStylesItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fragesymbol ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxStylesItem2() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxStylesItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehlersymbol ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxStylesItem3() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxStylesItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweissymbol ähnelt.
        '''</summary>
        Friend ReadOnly Property NotifyForm_ComboBoxStylesItem4() As String
            Get
                Return ResourceManager.GetString("NotifyForm_ComboBoxStylesItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Papa_Schlumpf_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Papa_Schlumpf_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die links oben ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_LineModusItem1() As String
            Get
                Return ResourceManager.GetString("Shape_LineModusItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die links unten ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_LineModusItem2() As String
            Get
                Return ResourceManager.GetString("Shape_LineModusItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die horizontale Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem1() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die vertikale Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem2() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die diagonale Linie ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem3() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechteck ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem4() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die gefülltes Rechteck ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem5() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ellipse ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem6() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die gefüllte Ellipse ähnelt.
        '''</summary>
        Friend ReadOnly Property Shape_ModusItem7() As String
            Get
                Return ResourceManager.GetString("Shape_ModusItem7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktion abgebrochen ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_AktionAbgebrochen() As String
            Get
                Return ResourceManager.GetString("Wizard_AktionAbgebrochen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktion abgeschlossen ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_AktionAbgeschlossen() As String
            Get
                Return ResourceManager.GetString("Wizard_AktionAbgeschlossen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie haben den Assistente abgeschlossen. ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_AssistenteAbgeschlossen() As String
            Get
                Return ResourceManager.GetString("Wizard_AssistenteAbgeschlossen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie haben den Assistenten abgebrochen. ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_AssistentenAbgebrochen() As String
            Get
                Return ResourceManager.GetString("Wizard_AssistentenAbgebrochen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Hilfe für die Seite {0} des Assistenten. ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_DieHilfeFürDieSeite0DesAssistenten() As String
            Get
                Return ResourceManager.GetString("Wizard_DieHilfeFürDieSeite0DesAssistenten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_Hilfe() As String
            Get
                Return ResourceManager.GetString("Wizard_Hilfe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nach dem Seitenwechsel ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_NachDemSeitenwechsel() As String
            Get
                Return ResourceManager.GetString("Wizard_NachDemSeitenwechsel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die neuer Index: {0} / alter Index: {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_NeuerIndex0AlterIndex1() As String
            Get
                Return ResourceManager.GetString("Wizard_NeuerIndex0AlterIndex1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vor dem Seitenwechsel ähnelt.
        '''</summary>
        Friend ReadOnly Property Wizard_VorDemSeitenwechsel() As String
            Get
                Return ResourceManager.GetString("Wizard_VorDemSeitenwechsel", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
